### ISSUE TITLE
Add project: Aboghazala/Hanash

### ISSUE THREAD

**Issue by PySimpleGUI** [mahmoud/awesome-python-applications#102]
## Basic info

**Application name**:
 Hanash

**Application repo link**: 
https://github.com/Aboghazala/Hanash

**Application home link**:
https://github.com/Aboghazala/Hanash

**Application description**: 
a general purpose multi-connections download manager based on python, pycurl, youtube_dl, and pysimplegui

## Qualifications

There are a ton of great Python projects out there, but what makes an
application "Awesome™"? Please check that all of the following criteria apply:

- [X] Free software with an online source repository.
- [X] Using Python for a considerable part of their functionality.
- [ ] Well-known, or at least prominently used in an identifiable niche.
- [X] Maintained or otherwise demonstrably still functional on relevant platforms.
- [X] An application, not a library or framework.

Note that installability via pip/PyPI and a developer-audience focus
may warrant a higher standard for inclusion, in keeping with the
spirit of the list:
http://sedimental.org/awesome_python_applications.html

## Additional notability info

It's amazing to use.  As soon as I copy a YouTube link in my browser, the program picks it up and begins downloading.  It's SUPER well polished.  GUIs are rare-ish in Python.  This one is multi-windowed with lots of stuff going on.  Impressive looking.

---

**Comment by mahmoud** [comment]
Hi @PySimpleGUI! I've added Hanash to the revisit list, which mostly consists of projects which are "young", i.e., with some combination of fewer than 100 commits or low committer count. It does look like a useful tool, keep those suggestions coming!

**Comment by PySimpleGUI** [comment]
Hi there!

The repo owner has renamed the project and moved it to a new location.

Because the application is a duplication of the popular "Internet Download Manager" he renamed it to be PyIDM 👍

https://github.com/pyIDM/pyIDM

I see that he's got over 100 commits now.  I dunno if that helps move him along in the process or not.

**Comment by PySimpleGUI** [comment]
Let me know if I need to open a new request since the project has moved and no longer matches what's in the 'revisit" list.
