### ISSUE TITLE
Add project: conan

### ISSUE THREAD

**Issue by akoeltringer** [mahmoud/awesome-python-applications#103]
## Basic info

**Application name**: Conan
**Application repo link**: https://github.com/conan-io/conan
**Application home link**: https://conan.io/
**Application description**: Decentralized, open-source (MIT), C/C++ package manager.

## Qualifications

There are a ton of great Python projects out there, but what makes an
application "Awesome™"? Please check that all of the following criteria apply:

- [X] Free software with an online source repository.
- [X] Using Python for a considerable part of their functionality.
- [X] Well-known, or at least prominently used in an identifiable niche.
- [X] Maintained or otherwise demonstrably still functional on relevant platforms.
- [X] An application, not a library or framework.

**Comment by mahmoud** [comment]
Good find, thank you!

**Comment by memsharded** [comment]
Thanks @mahmoud and @akoeltringer !
