### ISSUE TITLE
Add project: Home Assistant

### ISSUE THREAD

**Issue by cgtobi** [mahmoud/awesome-python-applications#105]
## Basic info

**Application name**: Home Assistant
**Application repo link**: https://github.com/home-assistant/home-assistant
**Application home link**: https://www.home-assistant.io/
**Application description**: Open source home automation that puts local control and privacy first.

## Qualifications

There are a ton of great Python projects out there, but what makes an
application "Awesome™"? Please check that all of the following criteria apply:

- [x] Free software with an online source repository.
- [x] Using Python for a considerable part of their functionality.
- [x] Well-known, or at least prominently used in an identifiable niche.
- [x] Maintained or otherwise demonstrably still functional on relevant platforms.
- [x] An application, not a library or framework.

Note that installability via pip/PyPI and a developer-audience focus
may warrant a higher standard for inclusion, in keeping with the
spirit of the list:
http://sedimental.org/awesome_python_applications.html

## Additional notability info

**Application demo link**: https://demo.home-assistant.io
**Application documentation link**: https://www.home-assistant.io/docs/

---

**Comment by mahmoud** [comment]
Thanks for those extra links! Home Assistant is very awesome indeed! :)

**Comment by cgtobi** [comment]
My pleasure. Thanks for maintaining this awesome awesome list. It's not
only linux btw. but works also fine on mac and windows as well.

**Comment by mahmoud** [comment]
I generally go off of what's in the installation instructions: https://www.home-assistant.io/getting-started/

It's kind of more a server architecture thing anyways, so it's a trickier one to categorize. :)
