### ISSUE TITLE
Add project: mlflow

### ISSUE THREAD

**Issue by obarbier** [mahmoud/awesome-python-applications#106]
## Basic info

mlflow
https://github.com/mlflow/mlflow
https://mlflow.org
Open source platform for the machine learning lifecycle 

## Qualifications

There are a ton of great Python projects out there, but what makes an
application "Awesome™"? Please check that all of the following criteria apply:

- [x] Free software with an online source repository.
- [x] Using Python for a considerable part of their functionality.
- [x] Well-known, or at least prominently used in an identifiable niche.
- [x] Maintained or otherwise demonstrably still functional on relevant platforms.
- [ ] An application, not a library or framework.

Note that installability via pip/PyPI and a developer-audience focus
may warrant a higher standard for inclusion, in keeping with the
spirit of the list:
http://sedimental.org/awesome_python_applications.html

## One more thing

Since you've made it this far, why not consider filing [a PR](https://github.com/mahmoud/awesome-python-applications/pulls)?

If your suggestion is a GitHub project, it's as easy as adding 2-3
lines to the `projects.yaml` file. There are comments and plenty of
examples in the file. Here's [an edit link](https://github.com/mahmoud/awesome-python-applications/edit/master/projects.yaml).

No pressure or anything, feel free to smack that submit button, too! Thanks again!

-->

**Comment by mahmoud** [comment]
Nice! Thanks!
