### ISSUE TITLE
Add project: Cura

### ISSUE THREAD

**Issue by paerts** [mahmoud/awesome-python-applications#118]
## Basic info

**Application name**: Cura
**Application repo link**: https://github.com/Ultimaker/Cura
**Application home link**: https://ultimaker.com/software/ultimaker-cura
**Application description**: Trusted by millions of users, Ultimaker Cura is the world’s most popular 3D printing software. Prepare prints with a few clicks, integrate with CAD software for an easier workflow, or dive into custom settings for in-depth control.

## Qualifications

There are a ton of great Python projects out there, but what makes an
application "Awesome™"? Please check that all of the following criteria apply:

- [v] Free software with an online source repository.
- [v] Using Python for a considerable part of their functionality.
- [v] Well-known, or at least prominently used in an identifiable niche.
- [v] Maintained or otherwise demonstrably still functional on relevant platforms.
- [v] An application, not a library or framework.

Note that installability via pip/PyPI and a developer-audience focus
may warrant a higher standard for inclusion, in keeping with the
spirit of the list:
http://sedimental.org/awesome_python_applications.html

## Additional notability info

---

**Comment by mahmoud** [comment]
Excellent find! Thank you!
