### ISSUE TITLE
Relationship to vinta/awesome-python?

### ISSUE THREAD

**Issue by eliotb** [mahmoud/awesome-python-applications#120]
It is not clear to me how if at all this list is related to the very similarly named https://github.com/vinta/awesome-python/

**Comment by mahmoud** [comment]
The APA is neither a derivative nor a successor to awesome-python. In fact, awesome-python already has [a doppelganger](https://github.com/uhub/awesome-python) (which also happens to be bigger, if less filtered), so it certainly doesn't need another.

@vinta's awesome-python is mostly libraries or frameworks (with a few tools) for developer usage. The APA list is all applications, for developer reference. I like to think they go hand-in-hand; most of the applications on the awesome-python-applications list use some combination of the libraries/frameworks on the awesome-python list.

I knew this would come up eventually so other comparisons can be found [here](https://github.com/mahmoud/awesome-python-applications/blob/master/TODO.md#other-lists). Hope this helps!

**Comment by mahmoud** [comment]
Closing for now, let me know if I need to clarify more. Thanks for the question!
