### ISSUE TITLE
Add project: GNS3

### ISSUE THREAD

**Issue by grelleum** [mahmoud/awesome-python-applications#123]
## Basic info

**Application name**: GNS3
**Application repo link**: https://github.com/GNS3
**Application home link**: https://www.gns3.com/
**Application description**: Graphical Network Simulator-3 (shortened to GNS3) is a network software emulator first released in 2008. It allows the combination of virtual and real devices, used to simulate complex networks.  

## Qualifications

There are a ton of great Python projects out there, but what makes an
application "Awesome™"? Please check that all of the following criteria apply:

- [X] Free software with an online source repository.
- [X] Using Python for a considerable part of their functionality.
- [X] Well-known, or at least prominently used in an identifiable niche.
- [X] Maintained or otherwise demonstrably still functional on relevant platforms.
- [X] An application, not a library or framework.

Note that installability via pip/PyPI and a developer-audience focus
may warrant a higher standard for inclusion, in keeping with the
spirit of the list:
http://sedimental.org/awesome_python_applications.html

## Additional notability info

From the Documentation:
https://docs.gns3.com/1PvtRW5eAb8RJZ11maEYD9_aLY8kkdhgaMB0wPCz8a38/index.html

GNS3 is used by hundreds of thousands of network engineers worldwide to emulate, configure, test and troubleshoot virtual and real networks. GNS3 allows you to run a small topology consisting of only a few devices on your laptop, to those that have many devices hosted on multiple servers or even hosted in the cloud.

GNS3 is open source, free software that you can download from http://gns3.com

It is actively developed and supported and has a growing community of over 800,000 members. By joining the GNS3 community you will be joining fellow students, network engineers, architects and others that have downloaded GNS3 over 10 million times to date. GNS3 is used in companies all over the world including Fortune 500 companies.

**Comment by mahmoud** [comment]
This one is suuuper awesome, thanks so much!
