### ISSUE TITLE
Add project: Docker Compose

### ISSUE THREAD

**Issue by Fazel94** [mahmoud/awesome-python-applications#158]
## Basic info

**Application name**: Docker Compose
**Application repo link**:  https://github.com/docker/compose
**Application home link**: https://docs.docker.com/compose/
**Application description**:  Compose is a tool for defining and running multi-container Docker applications. With Compose, you use a Compose file to configure your application's services.

## Qualifications

There are a ton of great Python projects out there, but what makes an
application "Awesome™"? Please check that all of the following criteria apply:

- [x] Free software with an online source repository.
- [x] Using Python for a considerable part of their functionality.
- [x] Well-known, or at least prominently used in an identifiable niche.
- [x] Maintained or otherwise demonstrably still functional on relevant platforms.
- [x] An application, not a library or framework.

Note that installability via pip/PyPI and a developer-audience focus
may warrant a higher standard for inclusion, in keeping with the
spirit of the list:
http://sedimental.org/awesome_python_applications.html

## Additional notability info
A lot of people use compose to test their multi-container docker setups easily.  
It is installed by default when you install docker.
20.9K GitHub stars and 3.4K forks.

---

**Comment by mahmoud** [comment]
Docker Compose has given me so many headaches over the years that the elision was a bit more than an oversight. But, you're right, it really does fit the bill, so onto the list it goes. Thanks!

**Comment by Fazel94** [comment]
I have a similar view, In my experience, most of the docker-related tools especially compose suffer from convenience issues, and the dev team actively refuses to address a lot of problems while adding features that are in the line of  Cloudgasms.
