### ISSUE TITLE
Question - Am I OK to use your code?

### ISSUE THREAD

**Issue by daPhipz** [mahmoud/awesome-python-applications#162]
This may sound like a silly question, but I don't want to be rude and just blindly copy everything you did without asking ;)

I want to create a similar list of projects, but with projects that need localization - I called it [LocalizeIt](https://github.com/daPhipz/LocalizeIt) :wink: 
My goal is to (eventually) provide a source for people who want to contribute to Open Source, but know very little to nothing about how to code.

A while back, I contributed to this project here and remembered how you created the list with the help of that `projects.yaml` file.
It would greatly help LocalizeIt, if I was allowed to include that mechanic into my project.
Of course, I would credit you guys at appropriate places! :heart_eyes:
Thanks for your consideration!

**Comment by mahmoud** [comment]
Yes, by all means! Sounds like a great effort. The list is generated by a parallel project called apatite: https://github.com/mahmoud/apatite

It's designed to be used from the command line, so you need a little proficiency to use it. But once you've got it installed (`pip install --user apatite`) it's just `apatite render` to make a README.md from a projects.yaml. Hope this helps!

**Comment by daPhipz** [comment]
Nice, thank you so so much!
Don't worry, as a Linux user, I know my way around the command line ;)
I will credit your work appropriately, of course!

By the way, I noticed that you don't have a LICENSE file in your repo - you may want to add one to clarify questions like mine ;)

**Comment by mahmoud** [comment]
Oh, good point. GPLv3 is specified in the setup.py, but I added a LICENSE.txt, hope that helps. Always remember, if the license in the repo doesn't work for your case, nothing stops you from asking for a different one. :)
