### ISSUE TITLE
add project: pre-commit

### ISSUE THREAD

**Issue by deronnax** [mahmoud/awesome-python-applications#171]
## Basic info

**Application name**: pre-commit
**Application repo link**: https://github.com/pre-commit/pre-commit
**Application home link**: https://[pre-commit](https://pre-commit.com/).com/
**Application description**: A framework for managing and maintaining multi-language pre-commit hooks.

## Qualifications

There are a ton of great Python projects out there, but what makes an
application "Awesome™"? Please check that all of the following criteria apply:

- [ x] Free software with an online source repository.
- [ x] Using Python for a considerable part of their functionality.
- [ x] Well-known, or at least prominently used in an identifiable niche.
- [ x] Maintained or otherwise demonstrably still functional on relevant platforms.
- [ x] An application, not a library or framework.

Note that installability via pip/PyPI and a developer-audience focus
may warrant a higher standard for inclusion, in keeping with the
spirit of the list:
http://sedimental.org/awesome_python_applications.html

## Additional notability info

---

Not sure it really qualifies as an application. It's an "application" to easily plug git hooks into python. I have encountered many times in a lot of python projects I worked in. 
Feel free to close the issue if it does not qualify

**Comment by mahmoud** [comment]
Phew, yeah definitely an application, how could I forget! Added, thanks!
