### ISSUE TITLE
add project: detect-secrets

### ISSUE THREAD

**Issue by deronnax** [mahmoud/awesome-python-applications#172]
## Basic info

**Application name**: detect-secrets
**Application repo link**: https://github.com/Yelp/detect-secrets
**Application home link**: https://github.com/Yelp/detect-secrets
**Application description**: An enterprise friendly way of detecting and preventing secrets in code.

## Qualifications

There are a ton of great Python projects out there, but what makes an
application "Awesome™"? Please check that all of the following criteria apply:

- [ ] Free software with an online source repository.
- [ ] Using Python for a considerable part of their functionality.
- [ ] Well-known, or at least prominently used in an identifiable niche.
- [ ] Maintained or otherwise demonstrably still functional on relevant platforms.
- [ ] An application, not a library or framework.

Note that installability via pip/PyPI and a developer-audience focus
may warrant a higher standard for inclusion, in keeping with the
spirit of the list:
http://sedimental.org/awesome_python_applications.html

## Additional notability info

---

An application meant to be used as a git hook to detect secrets committed in code before they get pushed (and thus definitely leaked). Very well done, simple and efficient. An industry standard. If you are not using it, your secrets probably already leaked and you are already at risk of being hacked (or already have and you don't know).

**Comment by mahmoud** [comment]
Another great entry, thanks for this, @deronnax!
