### ISSUE TITLE
Python tutorial 

### ISSUE THREAD

**Issue by davidtanko** [mahmoud/awesome-python-applications#184]
Can you teach me how to create app with python

**Comment by AndrewLighten** [comment]
> Can you teach me how to create app with python 

This is an impossibility broad question. There are plenty of Python learning resources on the web.

**Comment by shlomif** [comment]
@davidtanko : hi! there are links to resources for learning programming here: https://github.com/shlomif/Freenode-programming-channel-FAQ/blob/master/FAQ_with_ToC__generated.md (including for learning python; note that I comaintain that page). Otherewise, what kind of software application are you interested in writing: web, command-line, terminal, GUI, mobile, etc.?

**Comment by mahmoud** [comment]
@davidtanko asking the big questions! I'll offer that one of my favorite resources on this topic is https://www.fullstackpython.com/ Make sure to come back and check out APA for references once you're on your way :)
