### ISSUE TITLE
Add project: Iris & Oncall

### ISSUE THREAD

**Issue by jrgp** [mahmoud/awesome-python-applications#19]
## Basic info

**Application name**: Iris & Oncall
**Application repo link**: https://github.com/linkedin/iris and https://github.com/linkedin/oncall
**Application home link**:  https://iris.claims/ and https://oncall.tools/
**Application description**: Iris is used for multi-step pager escalations for incidents that arise during a company's monitoring. Oncall is a calendar app used for coordinating employee oncall schedules. They work together to function in the same niche and accomplish a similar goal as commercial tools like Pagerduty. 

## Qualifications

There are a ton of great Python projects out there, but what makes an
application "Awesome™"? Please check that all of the following criteria apply:

- [*] Free software with an online source repository.
- [*] Using Python for a considerable part of their functionality.
- [*] Well-known, or at least prominently used in an identifiable niche.
- [*] Maintained or otherwise demonstrably still functional on relevant platforms.
- [*] An application, not a library or framework.

## Additional notability info

These two tools are used extremely intensively within Linkedin (hundreds of incidents per day) and were open sourced early 2017. A talk was given at Monitorama in PDX in 2017. Both seem to fall under the "Communication" category.

**Comment by mahmoud** [comment]
Hey Joe! These look great. Definitely fit the bill of applications. I'm a little torn as to whether they go under `communication` or if they're more `dev.ops`. The audience definitely seems developer-oriented. I'll get it added ASAP, and I'll probably revisit the whole topic tree and categorizations later, so it won't be set in stone :)

Thanks again!
