### ISSUE TITLE
Add project: CherryTree

### ISSUE THREAD

**Issue by ibeex** [mahmoud/awesome-python-applications#20]
## Basic info

**Application name**: CherryTree
**Application repo link**: https://github.com/giuspen/cherrytree
**Application home link**: https://www.giuspen.com/cherrytree/
**Application description**: A hierarchical note taking application, featuring rich text and syntax highlighting, storing data in a single xml or sqlite file.

## Qualifications

There are a ton of great Python projects out there, but what makes an
application "Awesome™"? Please check that all of the following criteria apply:

- [x] Free software with an online source repository.
- [x] Using Python for a considerable part of their functionality.
- [x] Well-known, or at least prominently used in an identifiable niche.
- [x] Maintained or otherwise demonstrably still functional on relevant platforms.
- [x] An application, not a library or framework.

Note that installability via pip/PyPI and a developer-audience focus
may warrant a higher standard for inclusion, in keeping with the
spirit of the list:
http://sedimental.org/awesome_python_applications.html

**Comment by mahmoud** [comment]
Perfect, thank you!
