### ISSUE TITLE
Add project: Adventures of Dude in the Top-Down World

### ISSUE THREAD

**Issue by diguifi** [mahmoud/awesome-python-applications#23]
## Basic info

**Application name**: Adventures of Dude
**Application repo link**: https://github.com/diguifi/Dude-TopDown
**Application home link**: 
**Application description**: A game made in Python using PyGame. The game explores the differences between basic finite state machines AI versus a more complex AI based on genetic algorithms.

## Qualifications

There are a ton of great Python projects out there, but what makes an
application "Awesome™"? Please check that all of the following criteria apply:

- [x] Free software with an online source repository.
- [x] Using Python for a considerable part of their functionality.
- [ ] Well-known, or at least prominently used in an identifiable niche.
- [x] Maintained or otherwise demonstrably still functional on relevant platforms.
- [x] An application, not a library or framework.

Note that installability via pip/PyPI and a developer-audience focus
may warrant a higher standard for inclusion, in keeping with the
spirit of the list:
http://sedimental.org/awesome_python_applications.html

## Additional notability info

---

**Comment by diguifi** [comment]
[PR](https://github.com/mahmoud/awesome-python-applications/pull/25)

**Comment by mahmoud** [comment]
Closing per https://github.com/mahmoud/awesome-python-applications/pull/25#issuecomment-449453947
