### ISSUE TITLE
Add project: Abilian SBE

### ISSUE THREAD

**Issue by sfermigier** [mahmoud/awesome-python-applications#26]
## Basic info

**Application name**: Abilian SBE (Social Business Engine)
**Application repo link**: https://github.com/abilian/abilian-sbe
**Application home link**: https://github.com/abilian/abilian-sbe (same)
**Application description**: Abilian SBE (Social Business Engine) is a platform for social business applications, and more specifically collaborative / enterprise 2.0 business applications, such as enterprise social networks (ESN). Abilian SBE revolves around the concept of *communities*, which are collaborative spaces with services such as lightweight document management, discussions, wikis, user timelines, etc.

## Qualifications

There are a ton of great Python projects out there, but what makes an
application "Awesome™"? Please check that all of the following criteria apply:

- [x] Free software with an online source repository.
- [x] Using Python for a considerable part of their functionality.
- [x] Well-known, or at least prominently used in an identifiable niche.
- [x] Maintained or otherwise demonstrably still functional on relevant platforms.
- [x] An application, not a library or framework.

Note that installability via pip/PyPI and a developer-audience focus
may warrant a higher standard for inclusion, in keeping with the
spirit of the list:
http://sedimental.org/awesome_python_applications.html

## Additional notability info

Currently used as an intranet by non-profit organisations such as AFPC, CNLL (French Council for Free / Open Source Software), Systematic Paris-Region, Aquinetic, etc.

**Comment by mahmoud** [comment]
Very cool! Categorizing this one was a little tough. I think I'm probably going to make a "Business" section to feature Abillian, the ERP suites, and a couple business-focused CMSes. Thank you!
