### ISSUE TITLE
Possibly miscategorized projects 

### ISSUE THREAD

**Issue by pfalcon** [mahmoud/awesome-python-applications#34]
Not sure if you'd find this helpful, let me try.

`Dev` - > `Other Dev projects` is overbroad of course.

Blame me, but IPython and Jupyter Notebook are more close to "IDE" than to "other". Yeah, that a peculiar kind of IDE, but not everything should look and feel like TurboPascal 1.0, right? ;-)

Sage Math - Dev/Other Dev, really? That's clear Science.

Actually, I'm looking into this considering what would happen if I'd like to submit my cute piece https://github.com/pfalcon/ScratchABit/ . I'd have to shove it under "Security", and I'd hate that ;-).

**Comment by mahmoud** [comment]
Haha, fair points. None of the taxonomy is really set in stone, especially the topic angle, as it's the most subjective. I'll probably make those changes later today.

As for ScratchABit, yeah I'm not really sure what to put there. Probably need to make a hardware section at some point, if I can find enough open-source hardware-related applications of Python.
