### ISSUE TITLE
Add project: Script server (web UI for scripts)

### ISSUE THREAD

**Issue by bugy** [mahmoud/awesome-python-applications#35]
## Basic info

**Application name**: Script server
**Application repo link**: https://github.com/bugy/script-server
**Application home link**: https://github.com/bugy/script-server/wiki
**Application description**: the main responsibility of the tool is to provide web UI for scripts (python, bash, powershell, etc.). Additionally there is authentication, auditing, alerting, etc.

## Qualifications

There are a ton of great Python projects out there, but what makes an
application "Awesome™"? Please check that all of the following criteria apply:

- [x] Free software with an online source repository.
- [x] Using Python for a considerable part of their functionality.
- [ ] Well-known, or at least prominently used in an identifiable niche.
- [x] Maintained or otherwise demonstrably still functional on relevant platforms.
- [x] An application, not a library or framework.

In comparison to existing well-known projects with similar functionality (e.g. ansible, rundeck, jenkins) Script server is oriented on simplicity for the end user and interactivity.

## One more thing
Would be happy to submit a PR if the project is accepted :)

**Comment by mahmoud** [comment]
First off, really cool project. I know a few places where such a setup would have been useful. My first concern was about auth, but thanks to your docs/wiki, I see there's a story there. 

That said, your project is on the young side and it's got me thinking about usage and sustainability. Do you have a list of known users that would help further make the case? 

In either case, I think it's well on it's way, and is a good candidate for the list. I'll leave this ticket open for a bit longer so I can do a closer reading of the code and further consider script server's inclusion. Thanks for the submission!

**Comment by bugy** [comment]
Hi @mahmoud, thank you for the review and positive feedback! 

Unfortunately I don't have a list of active users. May be @yosefy, @csphoenix1, @muzzol are still using it and would be so kind to help here.

**Comment by shinebayar-g** [comment]
I've been using [script-server](https://github.com/bugy/script-server) for few weeks now and it's rapidly evolving project. Project owner @bugy is reliable person and concerned about this project's development.
Surely this project is not well known at the moment, but it's use case can be greatly wide.

My use case is, I'm cluster admin and developers don't have access to cluster. But they had to push updates to their projects. CI/CD could automate it, but developers preferred to push updates manually during night time. So I had to allow them to trigger some script on server. Script-server was perfect fit for my use case.

**Comment by yosefy** [comment]
we also use the script-server for deployments and data copy

**Comment by bugy** [comment]
Hi @mahmoud, did you have a time to look over the code? :)
The project is slowly growing and I would greatly appreciate, if you could include it the list of awesome apps :)

**Comment by muzzol** [comment]
hi @mahmoud , we use this project on production to manage several tasks on our whole infrastructure (about 300 servers/nodes).
@bugy has always been proactive, fast and reliable on solving problems and adding features, even with advanced issues like LDAP.

so for us is a big thumbs up :)

**Comment by mahmoud** [comment]
@muzzol I believe it! @bugy, it's clear to me that the project has come a long way since first submission. I'm by no means the only opinion that matters, but your users are happy and that demo server you set up is very very slick. I think the time has come for script server to be added to the APA. :)

**Comment by mahmoud** [comment]
And script server is in. Keep up the good work, @bugy. I'm a big fan :)

**Comment by bugy** [comment]
Hi @mahmoud thanks a lot!
