### ISSUE TITLE
Add project: SOFA statistics

### ISSUE THREAD

**Issue by eliotb** [mahmoud/awesome-python-applications#39]
## Basic info

**Application name**:
SOFA Statistics
**Application repo link**:
https://code.launchpad.net/sofastatistics
**Application home link**:
http://www.sofastatistics.com/home.php
**Application description**:
SOFA is a user-friendly statistics, analysis, & reporting program. It is free, with an emphasis on ease of use, learn as you go, and beautiful output.

## Qualifications

There are a ton of great Python projects out there, but what makes an
application "Awesome™"? Please check that all of the following criteria apply:

- [x] Free software with an online source repository.
- [x] Using Python for a considerable part of their functionality.
- [x] (maybe) Well-known, or at least prominently used in an identifiable niche.
- [x] Maintained or otherwise demonstrably still functional on relevant platforms.
- [x] An application, not a library or framework.

## Additional notability info
Cross platform, with windows, mac installers. Linux .deb and other installers.

Project claims 275,000 downloads

**Comment by mahmoud** [comment]
A fine submission. Added, with thanks :)
