### ISSUE TITLE
Add project: Quokka CMS

### ISSUE THREAD

**Issue by adrianoramos** [mahmoud/awesome-python-applications#41]
## Basic info

**Application name**: Quokka CMS
**Application repo link**: https://github.com/rochacbruno/quokka
**Application home link**: http://quokkaproject.org/
**Application description**: A lightweight framework to build CMS (Content Management System) as websites, portals, blogs, applications and anything related to publishing content to the web.

## Qualifications

There are a ton of great Python projects out there, but what makes an
application "Awesome™"? Please check that all of the following criteria apply:

- [x] Free software with an online source repository.
- [x] Using Python for a considerable part of their functionality.
- [ ] Well-known, or at least prominently used in an identifiable niche.
- [x] Maintained or otherwise demonstrably still functional on relevant platforms.
- [ ] An application, not a library or framework.

## Additional notability info

---

**Comment by mahmoud** [comment]
[Commented](https://github.com/mahmoud/awesome-python-applications/pull/42#issuecomment-450775917) over on the PR, #42. We'll track progress there. Thanks!
