### ISSUE TITLE
Add project: borg (actively developed fork (and de-facto successor) of attic

### ISSUE THREAD

**Issue by daPhipz** [mahmoud/awesome-python-applications#45]
## Basic info

**Application name**: BorgBackup
**Application repo link**: https://github.com/borgbackup/borg
**Application home link**: https://www.borgbackup.org/
**Application description**: Cited from their Github page: BorgBackup (short: Borg) is a deduplicating backup program. Optionally, it supports compression and authenticated encryption. The main goal of Borg is to provide an efficient and secure way to backup data. The data deduplication technique used makes Borg suitable for daily backups since only changes are stored. The authenticated encryption technique makes it suitable for backups to not fully trusted targets.

## Qualifications

There are a ton of great Python projects out there, but what makes an
application "Awesome™"? Please check that all of the following criteria apply:

- [X] Free software with an online source repository.
- [X] Using Python for a considerable part of their functionality.
Well, the majority of the code is written in C - but still, I would say 36% is a considerable part. If you are not interested in putting borg in the list, please consider removing attic however, because it is no longer actively developed (the latest commit on [their github](https://github.com/jborg/attic) is from May 2015).
- [X] Well-known, or at least prominently used in an identifiable niche.
- [x] Maintained or otherwise demonstrably still functional on relevant platforms.
- [X] An application, not a library or framework.

Note that installability via pip/PyPI and a developer-audience focus
may warrant a higher standard for inclusion, in keeping with the
spirit of the list:
http://sedimental.org/awesome_python_applications.html

---
I am also filing a pull request to this issue.

**Comment by mahmoud** [comment]
fixed in #46.
