### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by RomanKornev** [mahmoud/awesome-python-applications#49]
Contribution Guidelines with detailed instructions on how to add items to the list and how to generate the list itself would be nice.

Like here for example:
https://github.com/MaximAbramchuck/awesome-interview-questions/blob/master/contributing.md

**Comment by sunilkumarvalmiki** [comment]
@romankornev can i take the work.

**Comment by mahmoud** [comment]
Oh! Forgot to respond on this one. Took me a bit longer than expected, but this showed up a while back: https://github.com/mahmoud/awesome-python-applications/blob/master/CONTRIBUTING.md

Happy to take any help I can get :)
