### ISSUE TITLE
More programs

### ISSUE THREAD

**Issue by pylang** [mahmoud/awesome-python-applications#5]
I heard about this project on your TestandCode interview.

Here are some other python apps:

- **mu editor** - ([Home](https://codewith.mu/en/), [Repo](https://github.com/mu-editor/mu))a simple Python editor for beginner programmers. 
- **Friture** - ([Home](http://friture.org/), [Repo](https://github.com/tlecomte/friture))  application to visualize and analyze live audio data in real-time.
- **gPodder** - ([Home](https://gpodder.github.io/)) a simple, open source podcast client written in Python using GTK+. 
- **Camelot** - ([Blog](https://blog.socialcops.com/technology/engineering/camelot-python-library-pdf-data/?utm_campaign=tbc_camelot_oct18&utm_medium=social&utm_source=linkedIn&utm_content=blog_engg_camelot) [Repo](https://github.com/socialcopsdev/camelot/)) a Python Library to Extract Tabular Data from PDFs
- **livepython** - ([Repo](https://github.com/agermanidis/livepython)) Watch your Python run like a movie.
- **nbgrader** - ([Repo](https://github.com/jupyter/nbgrader)) A system for assigning and grading Jupyter notebooks; see command line tools

Non-Pure Python

- **GIMP** - ([Home](https://www.gimp.org/), [Ext. Docs](https://www.gimp.org/docs/python/index.html))  Open Source Image Editor
- **Dropbox** ([Home](https://www.dropbox.com/)) - desktop backup tool

**Comment by mahmoud** [comment]
Hey these are great! I'm still thinking about how to integrate the non-open-source options like dropbox, but these other ones look preettttty nice. I'll get them added shortly. Thanks!

**Comment by MosaicOrange** [comment]
### Some more to consider:
- **Modoboa** - ([Home](https://modoboa.org), [Repo](https://github.com/modoboa)) A solution to quickly deploy and manage a complete email server, compatible with latest standards and optimized for delivery and reputation protection.
- **Radicale** - ([Home](https://radicale.org), [Repo](https://github.com/Kozea/Radicale)) A Free and Open-Source CalDAV and CardDAV Server.
- **Pi-Hole** - ([Home](https://pi-hole.net), [Repo](https://github.com/pi-hole)) Network-wide ad blocking via your own Linux hardware.

**Comment by mahmoud** [comment]
I've added the majority of these, but I have some notes:

* livepython is still very early in its development, and but certainly one to watch
* camelot is a library, but I added excalibur, as it's an application based on that library by the same devs.
* nbgrader was already added in a separate issue :)

The rest are all indeed very awesome, this is excellent. I may have to enlist both of you to help flesh out the metadata shortly :)
