### ISSUE TITLE
Add project: Ralph (asset  management system)

### ISSUE THREAD

**Issue by ncoghlan** [mahmoud/awesome-python-applications#57]
## Basic info

**Application name**: Ralph
**Application repo link**: https://github.com/allegro/ralph
**Application home link**: https://ralph.allegro.tech/
**Application description**: Assets Management System
for Data Center and Back Office

## Qualifications

There are a ton of great Python projects out there, but what makes an
application "Awesome™"? Please check that all of the following criteria apply:

- [x] Free software with an online source repository.
- [x] Using Python for a considerable part of their functionality.
- [x] Well-known, or at least prominently used in an identifiable niche.
- [x] Maintained or otherwise demonstrably still functional on relevant platforms.
- [x] An application, not a library or framework.

## Additional notability info

While doing a survey of potential asset management tools a few years back, Ralph and the PHP OpenDCIM were basically the only open source options that came up - the other candidates were generally proprietary ones from hardware or operating system vendors.

**Comment by mahmoud** [comment]
Very nice! Looks really awesome at first blush, thank you!
