### ISSUE TITLE
Replace Vespene with OpsMop

### ISSUE THREAD

**Issue by ncoghlan** [mahmoud/awesome-python-applications#58]
Michael de Haan has indicated that he's going to discontinue Vespene development in order to focus on OpsMop instead: https://medium.com/@michaeldehaan/discontinuing-vespene-17fd9c0f3079

So rather than just adding OpsMop to the list here, it probably makes sense to remove Vespene at the same time.

**Comment by mahmoud** [comment]
Interesting, that's a new development. I saw both of them, but Vespene looked to be the more mature of the two. Judging by the current state of the repos and that blog post, I think replacement does make the most sense. Thanks for this!
