### ISSUE TITLE
Add project: Beaker (Linux hardware integration testing)

### ISSUE THREAD

**Issue by ncoghlan** [mahmoud/awesome-python-applications#59]
## Basic info

**Application name**: Beaker
**Application repo link**: https://git.beaker-project.org/cgit/beaker/tree/
**Application home link**: https://beaker-project.org/
**Application description**: Hardware integration testing system for Fedora & RHEL

## Qualifications

There are a ton of great Python projects out there, but what makes an
application "Awesome™"? Please check that all of the following criteria apply:

- [x] Free software with an online source repository.
- [x] Using Python for a considerable part of their functionality.
- [x] Well-known, or at least prominently used in an identifiable niche.
- [x] Maintained or otherwise demonstrably still functional on relevant platforms.
- [x] An application, not a library or framework.

## Additional notability info

It's biggest claim to fame is that it's the compatibility testing system for RHEL :)

**Comment by mahmoud** [comment]
A very awesome project indeed! Thank you!
