### ISSUE TITLE
Please add NBGrader to Education

### ISSUE THREAD

**Issue by GadgetSteve** [mahmoud/awesome-python-applications#6]
nbgrader is a Jupyer extension that lets Educators create, assign and grade assignments as Jupyter notebooks. Grading can be any mix of automatic marking, manual marking and manual annotation. Assignments can be created, assigned, performed, submitted, managed and graded from within Jupyter notebooks and can require the student to perform coding tasks in languages supported by Jupyter. Command line tools offer an efficient way for the instructor to generate, assign, release, collect, and grade notebooks.

Repo: https://github.com/jupyter/nbgrader
Docs: https://nbgrader.readthedocs.io/en/stable/
Licence: 3-Clause BSD

**Comment by mahmoud** [comment]
Very interesting! This is definitely an application, though it's unique in the list in that it targets Jupyter as its platform. All the more important that that architecture gets represented I suppose. Added, with thanks!
