### ISSUE TITLE
Add project: realtimefunc

### ISSUE THREAD

**Issue by Graywd** [mahmoud/awesome-python-applications#62]
## Basic info

**Application name**:realtimefunc
**Application repo link**:https://github.com/Graywd/realtimefunc
**Application home link**:https://pypi.org/project/realtimefunc/
**Application description**:A decorator is used to update a function at runtime to easy correct code in development without restart server.

## Qualifications

There are a ton of great Python projects out there, but what makes an
application "Awesome™"? Please check that all of the following criteria apply:

- [x] Free software with an online source repository.
- [x] Using Python for a considerable part of their functionality.
- [ ] Well-known, or at least prominently used in an identifiable niche.
- [ ] Maintained or otherwise demonstrably still functional on relevant platforms.
- [ ] An application, not a library or framework.

Note that installability via pip/PyPI and a developer-audience focus
may warrant a higher standard for inclusion, in keeping with the
spirit of the list:
http://sedimental.org/awesome_python_applications.html

**Comment by mahmoud** [comment]
Not an application, but a library, sorry!
