### ISSUE TITLE
Add project : game | Cows and Bulls game

### ISSUE THREAD

**Issue by god-s-perfect-idiot** [mahmoud/awesome-python-applications#67]
## Basic info
Cows and Bulls game
https://github.com/god-s-perfect-idiot/Cows-and-Bulls

This is a turn based two player game that relies mostly on the anaytic skills of the players wherein one player figures out the number guessed by the other before the other one does.

Runs using pygame.

**Application name**:
**Application repo link**:
**Application home link**:
**Application description**:

## Qualifications

There are a ton of great Python projects out there, but what makes an
application "Awesome™"? Please check that all of the following criteria apply:

- [ ] Free software with an online source repository.
- [ ] Using Python for a considerable part of their functionality.
- [ ] Well-known, or at least prominently used in an identifiable niche.
- [ ] Maintained or otherwise demonstrably still functional on relevant platforms.
- [ ] An application, not a library or framework.

Note that installability via pip/PyPI and a developer-audience focus
may warrant a higher standard for inclusion, in keeping with the
spirit of the list:
http://sedimental.org/awesome_python_applications.html

## Additional notability info

---

**Comment by mahmoud** [comment]
Hi Samar! As mentioned in the issue template, APA has a few guidelines for inclusion, and while this software is open-source python, it does not meet the notability guidelines. Keep up the good work and I'm sure you'll get there someday!
