### ISSUE TITLE
More Open Source Python Applications

### ISSUE THREAD

**Issue by hkmshb** [mahmoud/awesome-python-applications#7]
I heard about this project on the [Python Bytes podcast](https://pythonbytes.fm/) and thought the under listed programs can also be added:

**CMS**
**Kotti** - ([Home](http://kotti.pylonsproject.org/), [Repo](https://github.com/Kotti/Kotti)) a high-level, Pythonic web application framework.

**Package Managers**
**Poetry** - ([Home](https://poetry.eustace.io/), [Repo](https://github.com/sdispater/poetry)) Python dependency management and packaging made easy.

**Comment by joeblankenship1** [comment]
**Data Analysis**
**LibreQDA** - ([Home](https://libreqda.github.io/), [Repo](https://github.com/libreqda/libreQDA)) a Django-based application for qualitative data analysis.
**Orange** - ([Home](https://orange.biolab.si/), [Repo](https://github.com/biolab/orange3)) Open source machine learning and data visualization for novice and expert.

**Comment by mahmoud** [comment]
@hkmshb Excellent! Poetry is a good one for sure. Kotti seems to be more of a framework/library, not meant to be installed on its own. I'll defer on adding that one until I can do more research. Thank you!

@joeblankenship1 Orange is a great one I've used extensively, so it was one of the first ones on the list! :) I think it's under "science" right now. LibreQDA I'm not sure quite meets the (soon-to-be-published) criteria for being maintained, and I'm not really in a position to judge the extent of its use. If you care to provide some more justification, I'll consider putting it in right next to Orange :)
