### ISSUE TITLE
Add project: Polyaxon

### ISSUE THREAD

**Issue by mouradmourafiq** [mahmoud/awesome-python-applications#80]
## Basic info

**Application name**: Polyaxon
**Application repo link**: https://github.com/polyaxon/polyaxon
**Application home link**: https://docs.polyaxon.com
**Application description**: A platform for reproducible and scalable machine learning and deep learning on kubernetes.

## Qualifications

There are a ton of great Python projects out there, but what makes an
application "Awesome™"? Please check that all of the following criteria apply:

- [x] Free software with an online source repository.
- [x] Using Python for a considerable part of their functionality.
- [x] Well-known, or at least prominently used in an identifiable niche.
- [x] Maintained or otherwise demonstrably still functional on relevant platforms.
- [x] An application, not a library or framework.

Note that installability via pip/PyPI and a developer-audience focus
may warrant a higher standard for inclusion, in keeping with the
spirit of the list:
http://sedimental.org/awesome_python_applications.html

## Additional notability info

Polyaxon is used by several startups and Fortune 500 companies, it is also used at several academic and research institutions.

**Comment by mahmoud** [comment]
Hey Mourad! Polyaxon looks like a great project. I've added it, keep on being awesome!
