### ISSUE TITLE
Add project: json-streamer

### ISSUE THREAD

**Issue by kashifrazzaqui** [mahmoud/awesome-python-applications#81]
## Basic info

**Application name**: json-streamer
**Application repo link**: https://github.com/kashifrazzaqui/json-streamer
**Application home link**: https://github.com/kashifrazzaqui/json-streamer
**Application description**: A fast streaming JSON parser for Python that generates SAX-like events using yajl

## Qualifications

There are a ton of great Python projects out there, but what makes an
application "Awesome™"? Please check that all of the following criteria apply:

- [X] Free software with an online source repository.
- [X] Using Python for a considerable part of their functionality.
- [X] Well-known, or at least prominently used in an identifiable niche.
- [X] Maintained or otherwise demonstrably still functional on relevant platforms.
- [ ] An application, not a library or framework.

Note that installability via pip/PyPI and a developer-audience focus
may warrant a higher standard for inclusion, in keeping with the
spirit of the list:
http://sedimental.org/awesome_python_applications.html

## Additional notability info

---

**Comment by mahmoud** [comment]
Hi again Kashif! While jsonstreamer does have a module entrypoint (`-m jsonstreamer`), the default behavior is a little too trivial to call it an application. Looking at the examples, it seems that parser setup is pretty heavily programmatic, which again makes this more of a library, and thus not really suitable for this list. An interesting one nonetheless! Will keep it in mind for some of my future projects :)
