### ISSUE TITLE
Add project: themstates

### ISSUE THREAD

**Issue by kashifrazzaqui** [mahmoud/awesome-python-applications#82]
## Basic info

**Application name**: themstates
**Application repo link**: https://github.com/kashifrazzaqui/themstates
**Application home link**: https://github.com/kashifrazzaqui/themstates
**Application description**: A succinct but expressive state machine library

## Qualifications

There are a ton of great Python projects out there, but what makes an
application "Awesome™"? Please check that all of the following criteria apply:

- [X] Free software with an online source repository.
- [X] Using Python for a considerable part of their functionality.
- [ ] Well-known, or at least prominently used in an identifiable niche.
- [X] Maintained or otherwise demonstrably still functional on relevant platforms.
- [ ] An application, not a library or framework.

Note that installability via pip/PyPI and a developer-audience focus
may warrant a higher standard for inclusion, in keeping with the
spirit of the list:
http://sedimental.org/awesome_python_applications.html

## Additional notability info

---

**Comment by mahmoud** [comment]
Hey Kashif! Nice to meet a fellow state management fan. Unfortunately, themstates appears to be a library, so it's not really suitable for this list. However it looks interesting and I hope you keep up the good work!
