### ISSUE TITLE
Next batch of additions

### ISSUE THREAD

**Issue by mahmoud** [mahmoud/awesome-python-applications#91]
I'm just going to put this here so I can come back to these for additional research.

**Comment by mahmoud** [comment]
https://github.com/mozilla-services/socorro
https://github.com/edgedb/edgedb
https://github.com/nyaadevs/nyaa

**Comment by mahmoud** [comment]
https://github.com/hynek/doc2dash

**Comment by ngtvspc** [comment]
Maybe https://github.com/oaubert/advene? It's kinda niche though.

**Comment by mahmoud** [comment]
https://github.com/zopefoundation/ZEO is a zodb server, zodb is pretty mature and still being maintained.

**Comment by kietoparao** [comment]
https://github.com/whipper-team/whipper is a Python CD-DA ripper preferring accuracy over speed. I use it all the time in combination with MusicBrainz Picard, which is already on the list :)

**Comment by kietoparao** [comment]
https://github.com/tldr-pages/tldr is a simplified and community-driven man pages, it lets you quickly check how to use a command.
