### ISSUE TITLE
Cute "development" projects: PPCI and ScratchABit

### ISSUE THREAD

**Issue by pfalcon** [mahmoud/awesome-python-applications#96]
Please consider include cute @windelbouwman 's project: https://github.com/windelbouwman/ppci-mirror "Pure Python Compiler Infrastructure: A compiler for ARM, X86, MSP430, Xtensa, WebAssembly and more implemented in pure Python".

If you do, please also consider including my cute piece https://github.com/pfalcon/ScratchABit/ "Easily retargetable and hackable interactive disassembler with IDAPython-compatible plugin API"

Sorry for not filling in your cute questionnaire (it really sucks that I didn't). The only excuse is that there's not so many Python projects which cover those parts of software development as those 2 projects do.

Thanks!

**Comment by mahmoud** [comment]
Haha, I'm not sure what makes these projects "cute" but they are certainly interesting.

For both projects, it was not immediately obvious that they were applications (especially PPCI), but I dug around and found some docs (it would be nice if they were linked more prominently). I also checked and found sufficient third-party sources online expressing interest and usage. So I plan to include them.

Regarding ScratchABit, the last commit seems to be from 2018. But, given that you're the author, and recommending its addition, you're confirming its supported/maintained status?

**Comment by mahmoud** [comment]
They're added now :)

**Comment by pfalcon** [comment]
> For both projects, it was not immediately obvious that they were applications (especially PPCI)

Well, for ScratchABit, I don't know how to make it more obvious, put screenshot in front of the text? I still believe in a world where people read first ;-).

For PPCI, I agree that there're a lot of low-hanging fruit to improve the presentation, I spammed its bug tracker with suggestions (that 
particular is https://github.com/windelbouwman/ppci-mirror/issues/12), and I hope to help with that for as long as find time between maintaining my own stuff and @windelbouwman is responsive.

> Regarding ScratchABit, the last commit seems to be from 2018. But, given that you're the author, and recommending its addition, you're confirming its supported/maintained status?

Yeah, I consider the core functionality is there, and would like further development to happen in the form of plugins. Reverse engineering is also a niche area, so it's definitely not an everyday tool, for myself included, it's purpose to be just around for when it's needed ;-). I do test that it works with current Python versions, and actually pushed a commit to README saying that it's tested to work with CPython 3.3 thru 3.7.

> They're added now :)

Thanks!

**Comment by mahmoud** [comment]
> put screenshot in front of the text?

Not a bad idea! :) 1000 words, etc.

>  pushed a commit to README saying that it's tested to work with CPython 3.3 thru 3.7.

Excellent! Keep up the good work, and keep your eyes open for more applications, too! :)
